# Generated by Django 3.0.5 on 2021-03-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210324_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, verbose_name='autor recenzji')),
                ('content', models.TextField(verbose_name='treść recenzji')),
                ('is_recommended', models.BooleanField(verbose_name='polecam innym')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='recenzja filmu')),
            ],
        ),
    ]
